//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyaDesktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NyaDesktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;name&quot;:&quot;waifu.pics&quot;,&quot;apiInfo&quot;:&quot;url&quot;,&quot;SfwEndpoint&quot;:&quot;https://api.waifu.pics/sfw&quot;,&quot;NsfwEndpoint&quot;:&quot;https://api.waifu.pics/nsfw&quot;,&quot;SfwEndpoints&quot;:[&quot;waifu&quot;,&quot;neko&quot;,&quot;shinobu&quot;,&quot;megumin&quot;,&quot;bully&quot;,&quot;cuddle&quot;,&quot;cry&quot;,&quot;hug&quot;,&quot;awoo&quot;,&quot;kiss&quot;,&quot;lick&quot;,&quot;pat&quot;,&quot;smug&quot;,&quot;bonk&quot;,&quot;yeet&quot;,&quot;blush&quot;,&quot;smile&quot;,&quot;wave&quot;,&quot;highfive&quot;,&quot;handhold&quot;,&quot;nom&quot;,&quot;bite&quot;,&quot;glomp&quot;,&quot;slap&quot;,&quot;kill&quot;,&quot;kick&quot;,&quot;happy&quot;,&quot;wink&quot;,&quot;poke&quot;,&quot;dance&quot;,&quot;cringe&quot;],&quot;NsfwEndpoints&quot;:[&quot;waifu&quot;,&quot;neko&quot;,&quot;trap&quot;,&quot;blowjob&quot;]},{&quot;name&quot;:&quot;nekos.life&quot;,&quot;apiInfo&quot;:&quot;url&quot;,&quot;SfwEndpoint&quot;:&quot;https://nekos.life/api/v2/im [re....
        /// </summary>
        internal static string JSONendpoints {
            get {
                return ResourceManager.GetString("JSONendpoints", resourceCulture);
            }
        }
    }
}
